---
title: "Figure 1: All sample overview"
author: "Karol Nowicki-Osuch"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
    theme: paper
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in the data

```{r libraries, message=FALSE}
library(scran)
library(colorBlindness)
library(ggplot2)
library(RColorBrewer)
library(viridis)
library(cowplot)
library(scater)
library(TSCAN)
library(foreach)
library(doParallel)
```

# Figures

### Make bargraphs

```{r}
sce <- readRDS("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Final/All_sce_selected_corrected_after_exclusion2.rds")

colour.palet.boxplot <- c("NE" = "#990F0F", 
                  "NSCJ" = "#CC5151",
                  "SMG" = "#FFB2B2",
                  "GM" = "#E5B17E",
                  "BE" = "#99540F",
                  "BSCJ" = "#CC8E51",
                  
                  "NG" = "#6B990F",
                  "NGB" = "#A3CC51",
                  "NAG" = "#0F6B99",
                  "CAG" = "#2C85B2",
                  "CIM" = "#7EC3E5",
                  "GIM" = "#51A3CC",
                  
                  "ND" = "#260F99",
                  "Ileum" = "#422CB2",
                  "Colon" = "#6551CC",
                  "Rectum" = "#8F7EE5")
countsdata<-reshape2::melt(print(table(sce$Celltypes_global, colData(sce)$Tissue)))
colnames(countsdata)<-c("CellType", "Tissue", "Count")
countsdata$CellType<-factor(countsdata$CellType, levels = names(cell.order))
countsdata$Tissue <- factor(countsdata$Tissue, levels = names(colour.palet.boxplot))
countsdata$TissueType <- factor("Normal", levels = c("Normal", "Esophageal IM", "Stomach IM"))
countsdata$TissueType[countsdata$Tissue %in% c("BE", "BSCJ", "GM")] <- "Esophageal IM"
countsdata$TissueType[countsdata$Tissue %in% c("NAG", "CAG", "GIM", "CIM")] <- "Stomach IM"



countsdata<-countsdata[!(countsdata$CellType %in%   c(  "Superficial", 
                                                        "Intermediate",    
                                                        "Suprabasal",
                                                        "Basal",
                                                        # "SMG",
                                                        
                                                        "Fibroblasts",
                                                        "Endothelial",
                                                        
                                                        "B-Cells",
                                                        "T-Cells",
                                                        "Plasma-Cells",
                                                        "Macrophages",
                                                        "Mast",
                                                        
                                                        "Erythrocyte")),]
countsdata<-countsdata[!(countsdata$Tissue %in%   c("NE")),]
boxplot.celltypes<-ggplot(data = countsdata, aes(x = Tissue, y = Count, fill = CellType)) + geom_bar(position = "fill", stat = "identity") +   scale_fill_manual(values = cell.order) + theme_cowplot(12)  +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  facet_wrap(vars(TissueType), drop = TRUE,scales = "free_x", nrow = 1)+ theme(legend.position = "none")
plot(boxplot.celltypes)

ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_2/Boxplot.celltypes.pdf", boxplot.celltypes, device = "pdf", units="in", width=15, height=10, useDingbats = FALSE)

```

# T-SCAN analysis

# Perform pseudotime analysis

Here I will use TSCAN algorithm to reconstruct the trajectory following this manual: https://bioconductor.org/books/release/OSCA/trajectory-analysis.html


```{r}
# Read in all data
sce <- readRDS("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Final/All_sce_selected_corrected_after_exclusion2.rds")

# Perform PCA
HVG.genes<-modelGeneVar(sce, block = sce$Sample)
top.sce <- getTopHVGs(HVG.genes, n=2000)

set.seed(12345)
# PCA <- prcomp(t(corrected))
# save a slot
# reducedDims(sce)$PCA <- PCA$x
sce <- runPCA(sce, subset_row=top.sce) 


```

# run TSCAN

```{r}
# Run TSCAN on PCA data with outgroup option on and wiht cell types as clusters and with mnn mode on. Only focus on epithelial cells

cl <- makeCluster(7) #not to overload your computer
registerDoParallel(cl)

# Run in parallel wiht multiple values of outscale factor to identify a clear separation between cell types of glandular, squamous and columnar cell types

pseudo.mnn.list <-  foreach(i=c(2.5, 2.6,  2.7, 2.75, 2.8, 2.9, 3)) %dopar% {
  tmp = TSCAN::quickPseudotime(sce[,sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular") ], use.dimred="PCA", outgroup=TRUE, clusters =  sce$Global_cluster_selected[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular") ], with.mnn = TRUE,outscale = i)
  #do other things if you want
  return(tmp) 
}
#foreach(j=c(15, 100)) %:%
stopCluster(cl)

plot(pseudo.mnn.list[[2]]$mst)


#Aggregate data across tissue clusters
by.cluster<-aggregateAcrossCells(sce[,sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular") ], ids = sce$Global_cluster_selected[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular") ])

# Get line data between connected clusters
line.data <- reportEdges(by.cluster, mst=pseudo.mnn.list[[2]]$mst, clusters=NULL, use.dimred="umap_MinDist_0.2_N_Neighbors_15")

tscan.plot<-ggplot(data.frame(umap1 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,1],
                              umap2 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,2],
                              Alpha = ifelse(sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular"), "Epi", "other"))) +
  geom_point(aes(umap1, umap2, alpha = Alpha), size = 1, colour = "black") + # Plot all data in black as background
  scale_alpha_manual(values = c("Epi" = 1 , "other" = 0.01)) + # Change the alpha of the non-epithelial black dots to 1% to highlight only the epithelial cells
  geom_point(data= data.frame(umap1 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,1],
                              umap2 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,2],
                              Cell =  factor(sce$Celltypes_global, levels = names(cell.order))
  )[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular") ,], # Plot data for each epithelial cell again
  mapping = aes(umap1, umap2, colour = Cell), size = 0.5) + # make the dots smaller and colour by cell type
  scale_color_manual(values = cell.order) + # add cell type colour values
  geom_line(data=line.data, mapping=aes(x=dim1, y=dim2, group=edge)) + # add line data connecting the clusters (not cell types)
  # geom_text(data= aggregate(reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular"),], list(sce$Global_cluster_selected[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular")]), mean),
  #           mapping = aes(V1, V2, label = Group.1), colour = "red", size = 6) +
  #theme_cowplot(12) 
  guides(color=guide_legend(ncol=1, override.aes = list(size=4))) + #Plot legend in a single column
  theme_void()

print(tscan.plot)

ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_2/Allumap_withtscan.tiff", tscan.plot, device = "tiff", units="in", width=12, height=10)

tscan.plot.all<-ggplot(data.frame(umap1 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,1],
                                  umap2 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,2])) +
  # Alpha = ifelse(sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular"), "Epi", "other"))) +
  geom_point(aes(umap1, umap2), size = 1, colour = "black") + # Plot all data in black as background
  # scale_alpha_manual(values = c("Epi" = 1 , "other" = 0.01)) + # Change the alpha of the non-epithelial black dots to 1% to highlight only the epithelial cells
  geom_point(data= data.frame(umap1 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,1],
                              umap2 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,2],
                              Cell =  factor(sce$Celltypes_global, levels = names(cell.order))
  ), # Plot data for each epithelial cell again
  mapping = aes(umap1, umap2, colour = Cell), size = 0.5) + # make the dots smaller and colour by cell type
  scale_color_manual(values = cell.order) + # add cell type colour values
  geom_line(data=line.data, mapping=aes(x=dim1, y=dim2, group=edge)) + # add line data connecting the clusters (not cell types)
  # geom_text(data= aggregate(reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular"),], list(sce$Global_cluster_selected[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular")]), mean),
  #           mapping = aes(V1, V2, label = Group.1), colour = "red", size = 6) +
  #theme_cowplot(12) 
  guides(color=guide_legend(ncol=1, override.aes = list(size=4))) + #Plot legend in a single column
  theme_void()

print(tscan.plot.all)

ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_2/Allumap_all_withtscan.tiff", tscan.plot.all, device = "tiff", units="in", width=12, height=10)

```



# End Matter

To finish get session info:


```{r Endnote, include=TRUE, echo=TRUE, warning=FALSE, eval=TRUE, message=FALSE, tidy=TRUE}
sessionInfo()
```

