---
title: "Comparison of Fibroblasts"
author: "Karol Nowicki-Osuch"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
    theme: paper
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in the data

```{r libraries, message=FALSE}
library(scran)
library(colorBlindness)
library(ggplot2)
library(SingleR)
library(Rcpp)
library(RcppEigen)
library(ggsci)
library(scibet)
library(tidyverse)
# library(scater)
# library(DropletUtils)
library(openxlsx)
# library(Rtsne)
# library(umap)
library(RColorBrewer)
library(viridis)
library(cowplot)
# library(pheatmap)
# library(Seurat)
source("~/Dropbox/Postdoc/git/Gastric_IM//Analysis/Functions/auxiliary.R")
library(scater)
library(TSCAN)
# library(foreach)
library(doParallel)
library(MuSiC)
library(monocle3)
library(gridExtra)
library(grid)
```

```{r}

#Taken from colorBlindness::SteppedSequential5Steps
## colorBlindness::displayAvailablePalette(color="white")
colour.palet <- c("NE" = "#990F0F", 
                  "NSCJ" = "#CC5151",
                  "SMG" = "#FFB2B2",
                  "GM" = "#E5B17E",
                  "BE" = "#99540F",
                  "BSCJ" = "#CC8E51",
                  "NG" = "#6B990F",
                  "NGB" = "#A3CC51",
                  "NAG" = "#0F6B99",
                  "CAG" = "#2C85B2",
                  "GIM" = "#51A3CC",
                  "CIM" = "#7EC3E5",
                  "ND" = "#260F99",
                  "Ileum" = "#422CB2",
                  "Colon" = "#6551CC",
                  "Rectum" = "#8F7EE5")
# colour.palet <- c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))[1:length(unique(sce$Tissue))]
# names(colour.palet) <- sort(unique(sce$Tissue))
cell.order<-c(colorBlindness::SteppedSequential5Steps[6:10],rev(RColorBrewer::brewer.pal(n = 8,name = "Reds")) ,colorBlindness::SteppedSequential5Steps[c(11:13,15, 16,18, 21:25)], "grey60")

names(cell.order)<-c(
  "Superficial", 
  "Intermediate",    
  "Suprabasal",
  "Basal",
  "SMG",
  
  "Foveolar_Differentiated",
  "Foveolar_Intermediate",
  "Neck-Cells",
  "Chief",        
  "Parietal",
  "Enteroendocrine_CHGA",
  "Enteroendocrine_GHRL", 
  "Enteroendocrine_GAST",
  
  
  
  "Enterocytes",
  "Enterocytes_Intermediate",
  "Intestinal_Undifferentiated",
  "Goblet",
  
  "Fibroblasts",
  "Endothelial",
  
  "B-Cells",
  "T-Cells",
  "Plasma-Cells",
  "Macrophages",
  "Mast",
  
  "Erythrocyte"
)
```

```{r visualise}
sce <- readRDS("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Final/All_sce_selected_corrected_after_exclusion2.rds")

# Keep only columnar cell types
corrected<-metadata(sce)$corrected_2000[,sce$Celltypes_global == "Fibroblasts"]
sce <- sce[,sce$Celltypes_global == "Fibroblasts"]

# Recompute umap

# Compute tsne on corrected counts
set.seed(50014)
# tsne <- Rtsne(t(corrected), pca = FALSE)

cl <- makeCluster(7) #not to overload your computer
registerDoParallel(cl)

results <-  foreach(i=c(0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5)) %dopar% {
  tmp.umap = umap::umap(t(corrected), min_dist = i, n_neighbors = 15) #calling a function
  #do other things if you want
  return(tmp.umap) 
}
#foreach(j=c(15, 100)) %:%
stopCluster(cl)

names(results)<-paste("umap_MinDist", c(0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5), "N_Neighbors", 15, sep= "_" )
reducedDims(sce)<-lapply(results, function (x) {x$layout[,1:2]})




#Taken from colorBlindness::SteppedSequential5Steps
## colorBlindness::displayAvailablePalette(color="white")
colour.palet <- c("NE" = "#990F0F", 
                  "NSCJ" = "#CC5151",
                  "SMG" = "#FFB2B2",
                  "GM" = "#E5B17E",
                  "BE" = "#99540F",
                  "BSCJ" = "#CC8E51",
                  "NG" = "#6B990F",
                  "NGB" = "#A3CC51",
                  "NAG" = "#0F6B99",
                  "CAG" = "#2C85B2",
                  "GIM" = "#51A3CC",
                  "CIM" = "#7EC3E5",
                  "ND" = "#260F99",
                  "Ileum" = "#422CB2",
                  "Colon" = "#6551CC",
                  "Rectum" = "#8F7EE5")
# colour.palet <- c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))[1:length(unique(sce$Tissue))]
# names(colour.palet) <- sort(unique(sce$Tissue))
cell.order<-c(colorBlindness::SteppedSequential5Steps[6:10],rev(RColorBrewer::brewer.pal(n = 8,name = "Reds")) ,colorBlindness::SteppedSequential5Steps[c(11:13,15, 16,18, 21:25)], "grey60")

names(cell.order)<-c(
  "Superficial", 
  "Intermediate",    
  "Suprabasal",
  "Basal",
  "SMG",
  
  "Foveolar_Differentiated",
  "Foveolar_Intermediate",
  "Neck-Cells",
  "Chief",        
  "Parietal",
  "Enteroendocrine_CHGA",
  "Enteroendocrine_GHRL", 
  "Enteroendocrine_GAST",
  
  
  
  "Enterocytes",
  "Enterocytes_Intermediate",
  "Intestinal_Undifferentiated",
  "Goblet",
  
  "Fibroblasts",
  "Endothelial",
  
  "B-Cells",
  "T-Cells",
  "Plasma-Cells",
  "Macrophages",
  "Mast",
  
  "Erythrocyte"
)
set.seed(12345)
jumbled<-sample(ncol(sce), replace = FALSE)
sce<-sce[,jumbled]

# Clustering on corrected data in the selected tissues
g <- buildSNNGraph(corrected, k = 10)
clusters_selected <- igraph::cluster_louvain(g)$membership
clusters_selected <- clusters_selected[jumbled]
clusters <- sce$Global_cluster_selected

# Perform differential expression
markers <- findMarkers(sce, groups = clusters_selected, 
                       block = paste(colData(sce)$Patient, colData(sce)$Tissue, sep = "_"))


markers.spec <- lapply(markers, function(n){
  if(!is.na(n$Top[1]) & !is.nan(sum(as.matrix(n[1,4:ncol(n)])))){
    test_n <- !is.na(n[1,4:ncol(n)])[1,]
    cur_n <- n[n$FDR < 0.1 & apply(n[,4:ncol(n)], 1, function(x){sum(x[test_n] > 0)}) == sum(test_n),]
    if(nrow(cur_n) > 0){
      cur_n$GeneName <- rowData(sce)$Symbol[match(rownames(cur_n), rowData(sce)$ID)]
    }
  }
  else{
    cur_n <- NULL
  }
  cur_n
})

# Save clustering results
write.xlsx(markers.spec, paste("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Marker_genes/Fibroblasts/Marker_genes_combined_clean.xlsx", sep = ""))

sce$Fibroblast_clusters<-clusters_selected
# 
# reannot.clusters<-read.delim("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Additional_files/CellType_Global_clusters_20210702.txt")
# 
# sce$Celltypes_global<-reannot.clusters$CellType[match(sce$Global_cluster_selected, reannot.clusters$GlobalCluster)]


```

## Prepare data for visualisation

```{r}
sce$Fibroblast_Sarah <- NA
sce$Fibroblast_Sarah[sce$Fibroblast_clusters %in% c(7,2)] <- "S1"
sce$Fibroblast_Sarah[sce$Fibroblast_clusters %in% c(4,5,6)] <- "S2"
sce$Fibroblast_Sarah[sce$Fibroblast_clusters %in% c(1,3)] <- "S3"


sce.visualize<-sce
logcounts(sce.visualize)<-NULL
# randomise expression values nad moved htem to log2 space
counts(sce.visualize)<-logcounts(sce)#[,jumbled]

# Move Symbol to row name to keep it easy to loead into the data
rownames(sce.visualize)<-rowData(sce.visualize)$Symbol

colData(sce.visualize)<-colData(sce.visualize)[,c(4, 3, 1, 10:14, 16, 17,  19:28, 18, 8:9, 15)]
for(n in 1:(ncol(colData(sce.visualize))-4)) {
  colData(sce.visualize)[,n] <-  as.factor(colData(sce.visualize)[,n])
}   

for(n in (ncol(colData(sce.visualize))-3):(ncol(colData(sce.visualize))-1)) {
  colData(sce.visualize)[,n] <- log2(colData(sce.visualize)[,n] )
}




sceasy::convertFormat(sce.visualize, from="sce", to="anndata",
                      outFile="/home/karolno/Dropbox/Postdoc/2021-05-19_Gastric_IM/Visualisation/Fibroblasts.h5ad")

saveRDS(sce, "~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Final/All_sce_selected_corrected_Fibroblasts.rds")

```

## Plot the clustering of the Fibroblasts cells

```{r}

sce <- readRDS("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Final/All_sce_selected_corrected_Fibroblasts.rds")

umap.data<-reducedDims(sce)$umap_MinDist_0.1_N_Neighbors_15 
umap.min.max<-c(floor(min(umap.data[,1:2])), ceiling(max(umap.data[,1:2])))


# Visualise Clusters
Cluster.plot<-ggplot(data.frame(UMAP1 = umap.data[,1],
                                UMAP2 = umap.data[,2],
                                Cluster = factor(sce$Fibroblast_clusters))) +
  geom_point(aes(UMAP1, UMAP2), size = 1, color = "black") +
  geom_point(aes(UMAP1, UMAP2, colour = Cluster), size = 0.5) + 
  theme_void() +
  ylim(umap.min.max) +
  xlim(umap.min.max) +
  guides(color=guide_legend(ncol=2, override.aes = list(size=4))) +
  geom_text(data= aggregate(umap.data, list(sce$Fibroblast_clusters), mean),
            mapping = aes(V1, V2, label = Group.1), colour = "black", size = 6)
# scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))))
# scale_color_manual(values = colour.palet)

print(Cluster.plot)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Allumap_Clusters_Fibroblasts.tiff", Cluster.plot, device = "tiff", units="in", width=8, height=6)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Allumap_Clusters_Fibroblasts.pdf", Cluster.plot, device = "pdf", units="in", width=11, height=10, useDingbats = FALSE)

# Visualise Clusters
Cluster.plot.Sarah<-ggplot(data.frame(UMAP1 = umap.data[,1],
                                      UMAP2 = umap.data[,2],
                                      Cluster = factor(sce$Fibroblast_Sarah))) +
  geom_point(aes(UMAP1, UMAP2), size = 1, color = "black") +
  geom_point(aes(UMAP1, UMAP2, colour = Cluster), size = 0.5) + 
  theme_void() +
  ylim(umap.min.max) +
  xlim(umap.min.max) +
  guides(color=guide_legend(ncol=2, override.aes = list(size=4))) +
  geom_text(data= aggregate(umap.data, list(sce$Fibroblast_Sarah), mean),
            mapping = aes(V1, V2, label = Group.1), colour = "black", size = 6)
# scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))))
# scale_color_manual(values = colour.palet)

print(Cluster.plot.Sarah)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Allumap_Clusters_Sarahs.tiff", Cluster.plot.Sarah, device = "tiff", units="in", width=8, height=6)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Allumap_Clusters_Sarahs.pdf", Cluster.plot.Sarah, device = "pdf", units="in", width=11, height=10, useDingbats = FALSE)

# Visualise Clusters
tissues.plot<-ggplot(data.frame(UMAP1 = umap.data[,1],
                                UMAP2 = umap.data[,2],
                                tissue = factor(colData(sce)$Tissue, levels = names(colour.palet)))) +
  geom_point(aes(UMAP1, UMAP2), size = 1, color = "black") +
  geom_point(aes(UMAP1, UMAP2, colour = tissue), size = 0.5) + 
  theme_void() +
  ylim(umap.min.max) +
  xlim(umap.min.max) +
  # scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))))
  scale_color_manual(values = colour.palet)

print(tissues.plot)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Allumap_Tissues_Fibroblasts.tiff", tissues.plot, device = "tiff", units="in", width=8, height=6)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Allumap_Tissues_Fibroblasts.pdf", tissues.plot, device = "pdf", units="in", width=11, height=10, useDingbats = FALSE)


```

# Marker genes top 5 per clusgter

```{r}
genes <- lapply(markers.spec, function (x) rownames(x)[1:5])
genes <- genes[c(2, 7, 4, 6, 5, 1, 3)]
genes<- unique(unlist(genes))

#Get the expression values

meanexpression <- aggregate(as.data.frame(t(as.matrix(logcounts(sce)[rowData(sce)$ID %in% genes,]))), list(sce$Fibroblast_clusters), mean, drop = FALSE)



meanexpression <- reshape2::melt(meanexpression, id.vars = 1, variable.name = "gene", value.name = "mean_expression")
colnames(meanexpression)[1] <- c("Cluster")

propnozero <- function(x) {
  length(x[x>0])/length(x)
}
nonzeroexpression <- aggregate(as.data.frame(t(as.matrix(logcounts(sce)[rowData(sce)$ID %in% genes,]))), list(sce$Fibroblast_clusters), propnozero, drop = FALSE)

nonzeroexpression <- reshape2::melt(nonzeroexpression, id.vars = 1, variable.name = "gene", value.name = "Proportion")
colnames(nonzeroexpression)[1] <- c("Cluster")


expression.df <- merge(meanexpression, nonzeroexpression )
expression.df$gene <- factor(rowData(sce)$Symbol[match (expression.df$gene, rowData(sce)$ID)], levels = rowData(sce)$Symbol[match (genes, rowData(sce)$ID)])
# expression.df$Cell_type <- factor(expression.df$Cell_type, levels = c("Immune", "Stromal", "Basal", "Suprabasal", "Intermediate", "Superficial", "Undifferentiated","Foveolar_Intermediate", "Foveolar_differentiated", "Endocrine", "Novel"  ))
# expression.df$gene <- as.factor(expression.df$gene)

# expression.df$Tissue_type <- NA
# expression.df$Tissue_type[expression.df$Cell_type %in% c("Immune", "Stromal")] <- "Nonepithelial"
# expression.df$Tissue_type[expression.df$Cell_type %in% c("Basal", "Suprabasal", "Intermediate", "Superficial")] <- "Oesophageal"
# expression.df$Tissue_type[expression.df$Cell_type %in% c("Undifferentiated","Foveolar_Intermediate", "Foveolar_differentiated", "Endocrine")] <- "Gastric"
# expression.df$Tissue_type[expression.df$Cell_type %in% c("Novel")] <- "Novel"
expression.df$mean_expression2 <- ifelse(expression.df$mean_expression >3, yes = 3.1, no = expression.df$mean_expression )
expression.df$Cluster <- factor(expression.df$Cluster, levels = c(2, 7, 4, 6, 5, 1, 3))

for(n in colnames(expression.df)) {
  expression.df[is.na(expression.df[,n]),n]<-0
}

expression.plot <- ggplot(expression.df) + 
  geom_point(aes(y = Cluster, x = gene, size = Proportion, colour = mean_expression2)) + 
  theme_bw() + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black")) +  
  scale_size_continuous(limits=c(0, 1), breaks = c(0,.25,.5,.75,1)) +
  scale_color_viridis(option = "A")+
  # scale_color_manual(values = c("#4DBBD5FF", "grey40", "orange", "darkred" ))+
  theme(axis.text.x=element_text(angle = 45, vjust = 1, hjust = 1))


print(expression.plot)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Expression_plot_top5.pdf", expression.plot, device = "pdf", units="in", width=11, height=5, useDingbats = FALSE)



```



# Marker genes Tik's

```{r}

genes<- c("CD34", "POSTN", "ACTA2")

#Get the expression values

meanexpression <- aggregate(as.data.frame(t(as.matrix(logcounts(sce)[rowData(sce)$Symbol %in% genes,]))), list(sce$Fibroblast_clusters), mean, drop = FALSE)



meanexpression <- reshape2::melt(meanexpression, id.vars = 1, variable.name = "gene", value.name = "mean_expression")
colnames(meanexpression)[1] <- c("Cluster")

propnozero <- function(x) {
  length(x[x>0])/length(x)
}
nonzeroexpression <- aggregate(as.data.frame(t(as.matrix(logcounts(sce)[rowData(sce)$Symbol %in% genes,]))), list(sce$Fibroblast_clusters), propnozero, drop = FALSE)

nonzeroexpression <- reshape2::melt(nonzeroexpression, id.vars = 1, variable.name = "gene", value.name = "Proportion")
colnames(nonzeroexpression)[1] <- c("Cluster")


expression.df <- merge(meanexpression, nonzeroexpression )
expression.df$gene <- rowData(sce)$Symbol[match (expression.df$gene, rowData(sce)$ID)]
# expression.df$Cell_type <- factor(expression.df$Cell_type, levels = c("Immune", "Stromal", "Basal", "Suprabasal", "Intermediate", "Superficial", "Undifferentiated","Foveolar_Intermediate", "Foveolar_differentiated", "Endocrine", "Novel"  ))
expression.df$gene <- factor(expression.df$gene, levels = genes)

# expression.df$Tissue_type <- NA
# expression.df$Tissue_type[expression.df$Cell_type %in% c("Immune", "Stromal")] <- "Nonepithelial"
# expression.df$Tissue_type[expression.df$Cell_type %in% c("Basal", "Suprabasal", "Intermediate", "Superficial")] <- "Oesophageal"
# expression.df$Tissue_type[expression.df$Cell_type %in% c("Undifferentiated","Foveolar_Intermediate", "Foveolar_differentiated", "Endocrine")] <- "Gastric"
# expression.df$Tissue_type[expression.df$Cell_type %in% c("Novel")] <- "Novel"
expression.df$mean_expression2 <- ifelse(expression.df$mean_expression >2, yes = 2.1, no = expression.df$mean_expression )
expression.df$Cluster <- factor(expression.df$Cluster, levels = c(2, 7, 4, 6, 5, 1, 3))

for(n in colnames(expression.df)) {
  expression.df[is.na(expression.df[,n]),n]<-0
}

expression.plot <- ggplot(expression.df) + 
  geom_point(aes(y = Cluster, x = gene, size = Proportion, colour = mean_expression2)) + 
  theme_bw() + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black")) +  
  scale_size_continuous(limits=c(0, 1), breaks = c(0,.25,.5,.75,1)) +
  scale_color_viridis(option = "A")+
  # scale_color_manual(values = c("#4DBBD5FF", "grey40", "orange", "darkred" ))+
  theme(axis.text.x=element_text(angle = 45, vjust = 1, hjust = 1))


print(expression.plot)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Expression_plot_Tiks.pdf", expression.plot, device = "pdf", units="in", width=11, height=5, useDingbats = FALSE)



```


# Marker genes from Sarah's paper

```{r}

genes<- c("PDGFRA", "PDPN", "CD34", "FAP", "CD248", "COL1A1", "COL1A2", "FN1", "SPARC", "TNC", "ACTA2", "PDGFRB")

#Get the expression values

meanexpression <- aggregate(as.data.frame(t(as.matrix(logcounts(sce)[rowData(sce)$Symbol %in% genes,]))), list(sce$Fibroblast_clusters), mean, drop = FALSE)



meanexpression <- reshape2::melt(meanexpression, id.vars = 1, variable.name = "gene", value.name = "mean_expression")
colnames(meanexpression)[1] <- c("Cluster")

propnozero <- function(x) {
  length(x[x>0])/length(x)
}
nonzeroexpression <- aggregate(as.data.frame(t(as.matrix(logcounts(sce)[rowData(sce)$Symbol %in% genes,]))), list(sce$Fibroblast_clusters), propnozero, drop = FALSE)

nonzeroexpression <- reshape2::melt(nonzeroexpression, id.vars = 1, variable.name = "gene", value.name = "Proportion")
colnames(nonzeroexpression)[1] <- c("Cluster")


expression.df <- merge(meanexpression, nonzeroexpression )
expression.df$gene <- rowData(sce)$Symbol[match (expression.df$gene, rowData(sce)$ID)]
# expression.df$Cell_type <- factor(expression.df$Cell_type, levels = c("Immune", "Stromal", "Basal", "Suprabasal", "Intermediate", "Superficial", "Undifferentiated","Foveolar_Intermediate", "Foveolar_differentiated", "Endocrine", "Novel"  ))
expression.df$gene <- factor(expression.df$gene, levels = genes)

# expression.df$Tissue_type <- NA
# expression.df$Tissue_type[expression.df$Cell_type %in% c("Immune", "Stromal")] <- "Nonepithelial"
# expression.df$Tissue_type[expression.df$Cell_type %in% c("Basal", "Suprabasal", "Intermediate", "Superficial")] <- "Oesophageal"
# expression.df$Tissue_type[expression.df$Cell_type %in% c("Undifferentiated","Foveolar_Intermediate", "Foveolar_differentiated", "Endocrine")] <- "Gastric"
# expression.df$Tissue_type[expression.df$Cell_type %in% c("Novel")] <- "Novel"
expression.df$mean_expression2 <- ifelse(expression.df$mean_expression >2, yes = 2.1, no = expression.df$mean_expression )
expression.df$Cluster <- factor(expression.df$Cluster, levels = c(2, 7, 4, 6, 5, 1, 3))

for(n in colnames(expression.df)) {
  expression.df[is.na(expression.df[,n]),n]<-0
}

expression.plot <- ggplot(expression.df) + 
  geom_point(aes(y = Cluster, x = gene, size = Proportion, colour = mean_expression2)) + 
  theme_bw() + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black")) +  
  scale_size_continuous(limits=c(0, 1), breaks = c(0,.25,.5,.75,1)) +
  scale_color_viridis(option = "A")+
  # scale_color_manual(values = c("#4DBBD5FF", "grey40", "orange", "darkred" ))+
  theme(axis.text.x=element_text(angle = 45, vjust = 1, hjust = 1))


print(expression.plot)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Expression_plot_Sarahs.pdf", expression.plot, device = "pdf", units="in", width=11, height=5, useDingbats = FALSE)



```

```{r}
countsdata<-reshape2::melt(table(sce$Fibroblast_Sarah[sce$Study == "Fitz"], sce$Tissue[sce$Study == "Fitz"]))
colnames(countsdata)<-c("Cluster", "Tissue", "Proportion")
countsdata<-countsdata[!countsdata$Tissue %in% c("ND"),]
countsdata$Cluster<-as.factor(countsdata$Cluster)
countsdata$Tissue <- factor(countsdata$Tissue, levels = c("NE", "SMG", "NSCJ", "NG", "GM", "BE", "BSCJ", "CIM", "GIM"))
# countsdata<-countsdata[!(countsdata$Tissue %in%   c("NE")),]



boxplot.celltypes<-ggplot(data = countsdata, aes(x = Proportion, y = Tissue, fill = Cluster)) + geom_bar(position = "fill", stat = "identity") + theme_cowplot(12) +  scale_y_discrete(limits=rev)
plot(boxplot.celltypes)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Barchart_Fitz.pdf", boxplot.celltypes, device = "pdf", units="in", width=5, height=7.5, useDingbats = FALSE)
```

```{r}
countsdata<-reshape2::melt(table(sce$Fibroblast_Sarah[!sce$Study == "Fitz"], sce$Tissue[!sce$Study == "Fitz"]))
colnames(countsdata)<-c("Cluster", "Tissue", "Proportion")
countsdata<-countsdata[!countsdata$Tissue %in% c("ND"),]
countsdata$Cluster<-as.factor(countsdata$Cluster)
countsdata$Tissue <- factor(countsdata$Tissue, levels = c("NGB", "NAG", "CAG", "GIM"))
# countsdata<-countsdata[!(countsdata$Tissue %in%   c("NE")),]



boxplot.celltypes<-ggplot(data = countsdata, aes(x = Proportion, y = Tissue, fill = Cluster, label = Proportion)) + geom_bar(position = "fill", stat = "identity") + theme_cowplot(12) +  scale_y_discrete(limits=rev) + geom_text(aes(label = ifelse(Proportion <= 0 , NA, Proportion)), stat='identity', position=position_fill(vjust = .5), size = 10)
plot(boxplot.celltypes)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Barchart_Li_Ji.pdf", boxplot.celltypes, device = "pdf", units="in", width=5, height=7.5, useDingbats = FALSE)
```

```{r}

countsdata<-reshape2::melt(table(sce$Fibroblast_Sarah[!(sce$Sample %in% c("Patient15_SIGAH11_NG", "P6709_normal"))], paste(sce$Tissue, sce$Study, sce$Patient_type)[!(sce$Sample %in% c("Patient15_SIGAH11_NG", "P6709_normal"))]))
colnames(countsdata)<-c("Cluster", "Tissue", "Proportion")
countsdata<-countsdata[!countsdata$Tissue %in% c("ND Fitz Healthy", "NE Fitz Diseased"),]
countsdata$Cluster<-as.factor(countsdata$Cluster)
countsdata$Tissue <- factor(countsdata$Tissue, levels = c("NE Fitz Healthy", "SMG Fitz Healthy", "NSCJ Fitz Healthy", "NG Fitz Healthy",  "NG Fitz Diseased", "NGB Ji Healthy", "GM Fitz Diseased", "BE Fitz Diseased", "BSCJ Fitz Diseased", "NAG Li Diseased", "CAG Li Diseased", "CIM Fitz Diseased", "GIM Fitz Diseased", "GIM Li Diseased"))
# countsdata<-countsdata[!(countsdata$Tissue %in%   c("NE")),]



boxplot.celltypes<-ggplot(data = countsdata, aes(x = Tissue, y = Proportion, fill = Cluster, label = Proportion)) + 
  geom_bar(position = "fill", stat = "identity") + 
  theme_cowplot(12) +  
  # scale_x_discrete(limits=rev) +
  geom_text(aes(label = ifelse(Proportion <= 0 , NA, Proportion)), stat='identity', position=position_fill(vjust = .5), size = 6)
plot(boxplot.celltypes)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Barchart_All.pdf", boxplot.celltypes, device = "pdf", units="in", width=12, height=4, useDingbats = FALSE)
```


# Trajectory

## All cells

```{r}
# Load data 
sce <- readRDS("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Final/All_sce_selected_corrected_Fibroblasts.rds")


# Create monocle3 object
counts.data<-as.matrix(counts(sce))
colnames(counts.data)<-paste(colData(sce)$Barcode, colData(sce)$Sample, sep = "_")
cell.data<-colData(sce)
rownames(cell.data)<-paste(colData(sce)$Barcode, colData(sce)$Sample, sep = "_")
gene.data<-rowData(sce)
gene.data$gene_short_name<-gene.data$Symbol
cds <- new_cell_data_set(counts.data,
                         cell_metadata = cell.data,
                         gene_metadata = gene.data)

#Get PC
cds <- preprocess_cds(cds, num_dim = 50)

# Batch correct
cds <- align_cds(cds, alignment_group = "Sample", residual_model_formula_str = "~ MT.prop" )

# Get umap
cds <- reduce_dimension(cds)

# plot using building method
plot_cells(cds, label_groups_by_cluster=FALSE,  color_cells_by = "Fibroblast_clusters")


# Visualise Clusters
Cluster.plot<-ggplot(data.frame(UMAP1 = reducedDims(cds)$UMAP[,1],
                                UMAP2 = reducedDims(cds)$UMAP[,2],
                                Cluster = factor(cds$Fibroblast_clusters))) +
  geom_point(aes(UMAP1, UMAP2), size = 1, color = "black") +
  geom_point(aes(UMAP1, UMAP2, colour = Cluster), size = 0.5) + 
  theme_void() +
  # ylim(umap.min.max) +
  # xlim(umap.min.max) +
  guides(color=guide_legend(ncol=2, override.aes = list(size=4)))
# +
#   geom_text(data= aggregate(reducedDims(cds)$UMAP, list(cds$Fibroblast_clusters), mean),
#             mapping = aes(V1, V2, label = Group.1), colour = "black", size = 6)
# scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))))
# scale_color_manual(values = colour.palet)

print(Cluster.plot)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_umap_Clusters_Fibroblasts.tiff", Cluster.plot, device = "tiff", units="in", width=8, height=6)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_umap_Clusters_Fibroblasts.pdf", Cluster.plot, device = "pdf", units="in", width=8, height=6, useDingbats = FALSE)

# Visualise Clusters
Tissue.plot<-ggplot(data.frame(UMAP1 = reducedDims(cds)$UMAP[,1],
                               UMAP2 = reducedDims(cds)$UMAP[,2],
                               Tissue = factor(cds$Tissue, levels = names(colour.palet)))) +
  geom_point(aes(UMAP1, UMAP2), size = 1, color = "black") +
  geom_point(aes(UMAP1, UMAP2, colour = Tissue), size = 0.5) + 
  theme_void() +
  # ylim(umap.min.max) +
  # xlim(umap.min.max) +
  guides(color=guide_legend(ncol=2, override.aes = list(size=4))) +
  scale_color_manual(values = colour.palet)

# +
#   geom_text(data= aggregate(reducedDims(cds)$UMAP, list(cds$Fibroblast_clusters), mean),
#             mapping = aes(V1, V2, label = Group.1), colour = "black", size = 6)
# scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))))
# scale_color_manual(values = colour.palet)

print(Tissue.plot)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_umap_Tissue_Fibroblasts.tiff", Tissue.plot, device = "tiff", units="in", width=8, height=6)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_umap_Tissue_Fibroblasts.pdf", Tissue.plot, device = "pdf", units="in", width=8, height=6, useDingbats = FALSE)


Clusters.Sarah.plot<-ggplot(data.frame(UMAP1 = reducedDims(cds)$UMAP[,1],
                                       UMAP2 = reducedDims(cds)$UMAP[,2],
                                       Cluster = factor(cds$Fibroblast_Sarah))) +
  geom_point(aes(UMAP1, UMAP2), size = 1, color = "black") +
  geom_point(aes(UMAP1, UMAP2, colour = Cluster), size = 0.5) + 
  theme_void() +
  # ylim(umap.min.max) +
  # xlim(umap.min.max) +
  guides(color=guide_legend(ncol=2, override.aes = list(size=4))) #+
# geom_text(data= aggregate(reducedDims(cds)$UMAP, list(cds$Fibroblast_Sarah), mean),
#           mapping = aes(V1, V2, label = Group.1), colour = "black", size = 6)
# scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))))
# scale_color_manual(values = colour.palet)

print(Clusters.Sarah.plot)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_umap_Clusters_Sarah_Fibroblasts.tiff", Clusters.Sarah.plot, device = "tiff", units="in", width=8, height=6)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_umap_Clusters_Sarah_Fibroblasts.pdf", Clusters.Sarah.plot, device = "pdf", units="in", width=8, height=6, useDingbats = FALSE)


cds <- cluster_cells(cds)
plot_cells(cds, color_cells_by = "partition", group_label_size = 8)

# Visualise Partitions 
partitions.plot<-ggplot(data.frame(UMAP1 = reducedDims(cds)$UMAP[,1],
                                   UMAP2 = reducedDims(cds)$UMAP[,2],
                                   Partition = factor(partitions(cds)))) +
  geom_point(aes(UMAP1, UMAP2), size = 1, color = "black") +
  geom_point(aes(UMAP1, UMAP2, colour = Partition), size = 0.5) + 
  theme_void() +
  # ylim(umap.min.max) +
  # xlim(umap.min.max) +
  guides(color=guide_legend(ncol=2, override.aes = list(size=4))) +
  geom_text(data= aggregate(reducedDims(cds)$UMAP, list(partitions(cds)), mean),
            mapping = aes(V1, V2, label = Group.1), colour = "black", size = 6)
# scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))))
# scale_color_manual(values = colour.palet)

print(partitions.plot)




cds <- learn_graph(cds)

plot_cells(cds,
           color_cells_by = "Fibroblast_clusters",
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE)

cds <- order_cells(cds)


pseudotime.plot <- plot_cells(cds,
                              color_cells_by = "pseudotime",
                              label_cell_groups=FALSE,
                              label_leaves=FALSE,
                              label_branch_points=FALSE,
                              graph_label_size=5,
                              cell_size = .75) + theme_void()
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_umap_pseudotime_Fibroblasts.tiff", pseudotime.plot, device = "tiff", units="in", width=8, height=6)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_umap_pseudotime_Fibroblasts.pdf", pseudotime.plot, device = "pdf", units="in", width=8, height=6, useDingbats = FALSE)

# 
# cds_sub <- choose_graph_segments(cds)

```


## Correlation analysis on S1-2

```{r}
cds_sub <- cds[,cds$Fibroblast_Sarah %in% c("S1", "S2") & partitions(cds) == 1]

plot_cells(cds_sub,
           color_cells_by = "pseudotime",
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE,
           show_trajectory_graph = FALSE,
           cell_size = .75) + theme_void()

devsubset_pr_test_res <- graph_test(cds_sub, neighbor_graph="principal_graph", cores=32)
pr_deg_ids <- row.names(subset(subset_pr_test_res, q_value < 0.05))
gene_module_df <- find_gene_modules(cds_sub[pr_deg_ids,], resolution=0.001)
agg_mat <- aggregate_gene_expression(cds_sub, gene_module_df)
module_dendro <- hclust(dist(agg_mat))
gene_module_df$module <- factor(gene_module_df$module, 
                                levels = row.names(agg_mat)[module_dendro$order])
row.names(agg_mat) <- stringr::str_c("Module ", row.names(agg_mat))
agg_mat<- agg_mat[,order(pseudotime(cds_sub))]

ann.col<-data.frame("Pseudotime" = sort(pseudotime(cds_sub)),
                    "Tissue" = cds_sub$Tissue[order(pseudotime(cds_sub))],
                    "Cluster" = factor(cds_sub$Fibroblast_clusters[order(pseudotime(cds_sub))], levels = sort(unique(cds_sub$Fibroblast_clusters))))
rownames(ann.col)<-colnames(agg_mat)

colours.clusters<-brewer.pal(n = length(levels(ann.col$Cluster)), name = "Set1")
names(colours.clusters)<-levels(ann.col$Cluster)
colour.list<-list("Tissue" = colour.palet, "Cluster" = colours.clusters)
pheatmap::pheatmap(agg_mat, cluster_rows=TRUE, cluster_cols=FALSE,
                   scale="column", clustering_method="ward.D2",
                   fontsize=12,
                   show_colnames = FALSE,
                   annotation_col = ann.col, 
                   annotation_colors = colour.list, 
                   filename = "~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Modules_heatmap_S1-2.pdf", width = 23, height = 20, units = "cm", useDingbats = FALSE)
dev.off()

# module_dendro <- hclust(dist(agg_mat))
# gene_module_df$module <- factor(gene_module_df$module, 
#                                 levels = row.names(agg_mat)[module_dendro$order])
umap.modules<-plot_cells(cds_sub,
                         genes=gene_module_df,
                         label_cell_groups=FALSE,
                         show_trajectory_graph=FALSE,
                         cell_size = .75) + 
  theme_void()
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_umap_modules_S1-2_Fibroblasts.tiff", umap.modules, device = "tiff", units="in", width=8, height=6)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_umap_modules_S1-2_Fibroblasts.pdf", umap.modules, device = "pdf", units="in", width=8, height=6, useDingbats = FALSE)

plots<-list()
plots2<-list()

for (n in levels(gene_module_df$module)) {
  
  top10genes.module<-gene_module_df$id[gene_module_df$module == n]
  top10genes.module<-subset_pr_test_res[top10genes.module,]
  top10genes.module<-rownames(top10genes.module[order(top10genes.module$q_value, decreasing = FALSE),])[1:20]
  tmp<-cds_sub[rowData(cds_sub)$ID %in% top10genes.module,]
  tmp$Fibroblast_clusters<-as.factor(tmp$Fibroblast_clusters)
  
  
  
  plots[[n]]<-plot_genes_in_pseudotime(tmp,
                                       label_by_short_name = TRUE,
                                       # trend_formula = "~ splines::ns(pseudotime, df=3)",
                                       color_cells_by="Tissue",
                                       min_expr=0.5, 
                                       ncol = 2) +
    scale_color_manual(values = colour.palet) + 
    ggtitle(paste("Module", n)) +
    theme(plot.title = element_text(hjust = 0.5))
  
  plots2[[n]] <- plot_genes_in_pseudotime(tmp,
                                          label_by_short_name = TRUE,
                                          # trend_formula = "~ splines::ns(pseudotime, df=3)",
                                          color_cells_by="Fibroblast_clusters",
                                          min_expr=0.5, 
                                          ncol = 2)  +
    ggtitle(paste("Module", n)) +
    theme(plot.title = element_text(hjust = 0.5))
}

# ml <- do.call(marrangeGrob, c(plots, list(nrow = 1, ncol = 1)))
ml <- marrangeGrob(plots, nrow=1, ncol=1)

# ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_topgenes_tissue_Fibroblasts.pdf", ml, device = "pdf", units="in", width=8, height=6, useDingbats = FALSE)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_topgenes_tissue_S1-2_Fibroblasts.pdf", ml, device = "pdf", width = 21, height = 29.7, units = "cm", useDingbats = FALSE)


# ml <- do.call(marrangeGrob, c(plots, list(nrow = 1, ncol = 1)))
ml2 <- marrangeGrob(plots2, nrow=1, ncol=1)

# ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_topgenes_tissue_Fibroblasts.pdf", ml, device = "pdf", units="in", width=8, height=6, useDingbats = FALSE)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_topgenes_Cluster_S1-2_Fibroblasts.pdf", ml2, device = "pdf", width = 21, height = 29.7, units = "cm", useDingbats = FALSE)



```



## Correlation analysis on S3

```{r}
cds_sub <- cds[,cds$Fibroblast_Sarah %in% c("S3") & partitions(cds) == 2]

plot_cells(cds_sub,
           color_cells_by = "Fibroblast_clusters",
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE,
           show_trajectory_graph = FALSE,
           cell_size = .75) + theme_void()

devsubset_pr_test_res <- graph_test(cds_sub, neighbor_graph="principal_graph", cores=32)
pr_deg_ids <- row.names(subset(subset_pr_test_res, q_value < 0.05))
gene_module_df <- find_gene_modules(cds_sub[pr_deg_ids,], resolution=0.001)
agg_mat <- aggregate_gene_expression(cds_sub, gene_module_df)
module_dendro <- hclust(dist(agg_mat))
gene_module_df$module <- factor(gene_module_df$module, 
                                levels = row.names(agg_mat)[module_dendro$order])
row.names(agg_mat) <- stringr::str_c("Module ", row.names(agg_mat))
agg_mat<- agg_mat[,order(pseudotime(cds_sub))]

ann.col<-data.frame("Pseudotime" = sort(pseudotime(cds_sub)),
                    "Tissue" = cds_sub$Tissue[order(pseudotime(cds_sub))],
                    "Cluster" = factor(cds_sub$Fibroblast_clusters[order(pseudotime(cds_sub))], levels = sort(unique(cds_sub$Fibroblast_clusters))))
rownames(ann.col)<-colnames(agg_mat)

colours.clusters<-brewer.pal(n = 7, name = "Set1")
names(colours.clusters)<-1:7
colour.list<-list("Tissue" = colour.palet, "Cluster" = colours.clusters)
pheatmap::pheatmap(agg_mat, cluster_rows=TRUE, cluster_cols=FALSE,
                   scale="column", clustering_method="ward.D2",
                   fontsize=12,
                   show_colnames = FALSE,
                   annotation_col = ann.col, 
                   annotation_colors = colour.list, 
                   filename = "~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Modules_heatmap_S3.pdf", width = 23, height = 20, units = "cm", useDingbats = FALSE)
dev.off()

# module_dendro <- hclust(dist(agg_mat))
# gene_module_df$module <- factor(gene_module_df$module, 
#                                 levels = row.names(agg_mat)[module_dendro$order])
umap.modules<-plot_cells(cds_sub,
                         genes=gene_module_df,
                         label_cell_groups=FALSE,
                         show_trajectory_graph=FALSE,
                         cell_size = .75) + 
  theme_void()
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_umap_modules_S3_Fibroblasts.tiff", umap.modules, device = "tiff", units="in", width=8, height=6)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_umap_modules_S3_Fibroblasts.pdf", umap.modules, device = "pdf", units="in", width=8, height=6, useDingbats = FALSE)

plots<-list()
plots2<-list()

for (n in levels(gene_module_df$module)) {
  
  top10genes.module<-gene_module_df$id[gene_module_df$module == n]
  top10genes.module<-subset_pr_test_res[top10genes.module,]
  top10genes.module<-rownames(top10genes.module[order(top10genes.module$q_value, decreasing = FALSE),])[1:20]
  tmp<-cds_sub[rowData(cds_sub)$ID %in% top10genes.module,]
  tmp$Fibroblast_clusters<-as.factor(tmp$Fibroblast_clusters)
  
  
  
  plots[[n]]<-plot_genes_in_pseudotime(tmp,
                                       label_by_short_name = TRUE,
                                       # trend_formula = "~ splines::ns(pseudotime, df=3)",
                                       color_cells_by="Tissue",
                                       min_expr=0.5, 
                                       ncol = 2) +
    scale_color_manual(values = colour.palet) + 
    ggtitle(paste("Module", n)) +
    theme(plot.title = element_text(hjust = 0.5))
  
  plots2[[n]] <- plot_genes_in_pseudotime(tmp,
                                          label_by_short_name = TRUE,
                                          # trend_formula = "~ splines::ns(pseudotime, df=3)",
                                          color_cells_by="Fibroblast_clusters",
                                          min_expr=0.5, 
                                          ncol = 2)  +
    ggtitle(paste("Module", n)) +
    theme(plot.title = element_text(hjust = 0.5))
}

# ml <- do.call(marrangeGrob, c(plots, list(nrow = 1, ncol = 1)))
ml <- marrangeGrob(plots, nrow=1, ncol=1)

# ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_topgenes_tissue_Fibroblasts.pdf", ml, device = "pdf", units="in", width=8, height=6, useDingbats = FALSE)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_topgenes_tissue_S3_Fibroblasts.pdf", ml, device = "pdf", width = 21, height = 29.7, units = "cm", useDingbats = FALSE)


# ml <- do.call(marrangeGrob, c(plots, list(nrow = 1, ncol = 1)))
ml2 <- marrangeGrob(plots2, nrow=1, ncol=1)

# ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_topgenes_tissue_Fibroblasts.pdf", ml, device = "pdf", units="in", width=8, height=6, useDingbats = FALSE)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_topgenes_Cluster_S3_Fibroblasts.pdf", ml2, device = "pdf", width = 21, height = 29.7, units = "cm", useDingbats = FALSE)
```

## Expression of previous genes

```{r}
markers.spec <- lapply(as.list(1:7), function (x) read.xlsx(paste("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Marker_genes/Fibroblasts/Marker_genes_combined_clean.xlsx", sep = ""), x))

genes <- lapply(markers.spec, function (x) x[1:5,"GeneName"])
genes <- genes[c(2, 7, 4, 6, 5, 1, 3)]
genes<- unique(unlist(genes))


cds_sub <- cds[,cds$Fibroblast_Sarah %in% c("S3") & partitions(cds) == 2]


gene_mat <- SingleCellExperiment::counts(cds_sub[rowData(cds_sub)$Symbol %in% genes,]) + 1
gene_mat <- log2(Matrix::t(Matrix::t(gene_mat)/size_factors(cds_sub[rowData(cds_sub)$Symbol %in% genes,])))

row.names(gene_mat) <-rowData(cds_sub)$Symbol[ rowData(cds_sub)$Symbol %in% genes]
gene_mat<- gene_mat[genes,]
gene_mat<- gene_mat[,order(pseudotime(cds_sub))]

ann.col<-data.frame("Pseudotime" = sort(pseudotime(cds_sub)),
                    "Tissue" = cds_sub$Tissue[order(pseudotime(cds_sub))],
                    "Cluster" = factor(cds_sub$Fibroblast_clusters[order(pseudotime(cds_sub))], levels = sort(unique(cds_sub$Fibroblast_clusters))))
rownames(ann.col)<-colnames(gene_mat)

cds_sub2 <- cds[,cds$Fibroblast_Sarah %in% c("S1", "S2") & partitions(cds) == 1]

gene_mat2 <- SingleCellExperiment::counts(cds_sub2[rowData(cds_sub2)$Symbol %in% genes,]) + 1
gene_mat2 <- log2(Matrix::t(Matrix::t(gene_mat2)/size_factors(cds_sub2[rowData(cds_sub2)$Symbol %in% genes,])))

row.names(gene_mat2) <-rowData(cds_sub2)$Symbol[ rowData(cds_sub2)$Symbol %in% genes]
gene_mat2<- gene_mat2[genes,]
gene_mat2<- gene_mat2[,order(pseudotime(cds_sub2))]

ann.col2<-data.frame("Pseudotime" = sort(pseudotime(cds_sub2)),
                     "Tissue" = cds_sub2$Tissue[order(pseudotime(cds_sub2))],
                     "Cluster" = factor(cds_sub2$Fibroblast_clusters[order(pseudotime(cds_sub2))], levels = sort(unique(cds_sub2$Fibroblast_clusters))))
rownames(ann.col2)<-colnames(gene_mat2)

gene_mat <- cbind(gene_mat2, gene_mat)
ann.col <- rbind(ann.col2,ann.col)

colours.clusters<-brewer.pal(n = 7, name = "Set1")
names(colours.clusters)<-1:7
colour.list<-list("Tissue" = colour.palet, "Cluster" = colours.clusters)
pheatmap::pheatmap(gene_mat, cluster_rows=FALSE, cluster_cols=FALSE,
                   scale="row", clustering_method="ward.D2",
                   fontsize=12,
                   show_colnames = FALSE,
                   annotation_col = ann.col, 
                   annotation_colors = colour.list, 
                   filename = "~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Genes_heatmap_S1-3.pdf", width = 23, height = 20, units = "cm", useDingbats = FALSE)
dev.off()


umap.gene.plot<-plot_cells(cds, genes=genes,
                           show_trajectory_graph=FALSE,
                           label_cell_groups=FALSE,
                           label_leaves=FALSE)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_5/Monocle_Genes_umap_S1-3_Fibroblasts.pdf", umap.gene.plot, device = "pdf", width = 29.7, height = 29.7, units = "cm", useDingbats = FALSE)


```

# End Matter

To finish get session info:

```{r Endnote, include=TRUE, echo=TRUE, warning=FALSE, eval=TRUE, message=FALSE, tidy=TRUE}
sessionInfo()
```
