---
title: "Figure 1: All sample overview"
author: "Karol Nowicki-Osuch"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
    theme: paper
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in the data

```{r libraries, message=FALSE}
library(scran)
library(colorBlindness)
library(ggplot2)
library(RColorBrewer)
library(viridis)
library(cowplot)
library(scater)
library(TSCAN)
library(foreach)
library(doParallel)
```

# Figures

## General overview

```{r visualise}
sce <- readRDS("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Final/All_sce_selected_corrected_after_exclusion2.rds")

#Taken from colorBlindness::SteppedSequential5Steps
## colorBlindness::displayAvailablePalette(color="white")
colour.palet <- c("NE" = "#990F0F", 
                  "NSCJ" = "#CC5151",
                  "SMG" = "#FFB2B2",
                  "BE" = "#99540F",
                  "BSCJ" = "#CC8E51",
                  "GM" = "#E5B17E",
                  "NG" = "#6B990F",
                  "NGB" = "#A3CC51",
                  "NAG" = "#0F6B99",
                  "CAG" = "#2C85B2",
                  "GIM" = "#51A3CC",
                  "CIM" = "#7EC3E5",
                  "ND" = "#260F99",
                  "Ileum" = "#422CB2",
                  "Colon" = "#6551CC",
                  "Rectum" = "#8F7EE5")
# colour.palet <- c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))[1:length(unique(sce$Tissue))]
# names(colour.palet) <- sort(unique(sce$Tissue))


set.seed(12345)
jumbled<-sample(ncol(sce), replace = FALSE)
sce<-sce[,jumbled]
# Save clustering in new slot
clusters <- sce$Global_cluster_selected

umap.data<-reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15 
umap.min.max<-c(floor(min(umap.data[,1:2])), ceiling(max(umap.data[,1:2])))
# Visualise number of genes
print(ggplot(data.frame(UMAP1 = umap.data[,1],
                        UMAP2 = umap.data[,2],
                        Genes = log10(sce$detected))) + 
        theme_cowplot(12) +
        ylim(umap.min.max) +
        xlim(umap.min.max) +
        geom_point(aes(UMAP1, UMAP2, colour = Genes), size = 0.5) +
        scale_colour_viridis(option = "B")
)


# Visualise number of UMIs
print(ggplot(data.frame(UMAP1 = umap.data[,1],
                        UMAP2 = umap.data[,2],
                        UMIs = log10(sce$total))) + 
        theme_cowplot(12) +
        ylim(umap.min.max) +
        xlim(umap.min.max) +
        geom_point(aes(UMAP1, UMAP2, colour = UMIs), size = 0.5) +
        scale_colour_viridis(option = "B")
)
# Visualise size factors
print(ggplot(data.frame(UMAP1 = umap.data[,1],
                        UMAP2 = umap.data[,2],
                        Size = log10(sizeFactors(sce)))) + 
        theme_cowplot(12) +
        ylim(umap.min.max) +
        xlim(umap.min.max) +
        geom_point(aes(UMAP1, UMAP2, colour = Size), size = 0.5) +
        scale_colour_viridis(option = "B")
)

# Visualise cluster
print(ggplot(data.frame(UMAP1 = umap.data[,1],
                        UMAP2 = umap.data[,2],
                        clusters = as.factor(clusters))) + 
        theme_cowplot(12) +
        ylim(umap.min.max) +
        xlim(umap.min.max) +
        geom_point(aes(UMAP1, UMAP2, colour = clusters), size = 0.5))

# Visualise tissues
tissues.plot<-ggplot(data.frame(UMAP1 = umap.data[,1],
                                UMAP2 = umap.data[,2],
                                tissue = factor(colData(sce)$Tissue, levels = names(colour.palet)))) +
  geom_point(aes(UMAP1, UMAP2), size = 1, color = "black") +
  geom_point(aes(UMAP1, UMAP2, colour = tissue), size = 0.5) + 
  theme_cowplot(12) +
  ylim(umap.min.max) +
  xlim(umap.min.max) +
  # scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))))
  scale_color_manual(values = colour.palet)

tissues.plot<-ggplot(data.frame(UMAP1 = umap.data[,1],
                                UMAP2 = umap.data[,2],
                                tissue = factor(colData(sce)$Tissue, levels = names(colour.palet)))) +
  geom_point(aes(UMAP1, UMAP2), size = 1, color = "black") +
  geom_point(aes(UMAP1, UMAP2, colour = tissue), size = 0.5) + 
  theme_void() +
  ylim(umap.min.max) +
  xlim(umap.min.max) +
  # scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))))
  scale_color_manual(values = colour.palet)

print(tissues.plot)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/Allumap.tiff", tissues.plot, device = "tiff", units="in", width=11, height=10)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/Allumap.pdf", tissues.plot, device = "pdf", units="in", width=11, height=10, useDingbats = FALSE)


# Visualise tissues
Cluster.plot<-ggplot(data.frame(UMAP1 = umap.data[,1],
                                UMAP2 = umap.data[,2],
                                Cluster = factor(sce$Global_cluster_selected))) +
  geom_point(aes(UMAP1, UMAP2), size = 1, color = "black") +
  geom_point(aes(UMAP1, UMAP2, colour = Cluster), size = 0.5) + 
  theme_void() +
  ylim(umap.min.max) +
  xlim(umap.min.max) +
  guides(color=guide_legend(ncol=2, override.aes = list(size=4))) +
  geom_text(data= aggregate(reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15, list(sce$Global_cluster_selected), mean),
            mapping = aes(V1, V2, label = Group.1), colour = "black", size = 6) 
# scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))))
# scale_color_manual(values = colour.palet)

print(Cluster.plot)


ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/Allumap_Clusters.tiff", Cluster.plot, device = "tiff", units="in", width=11, height=10)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/Allumap_Clusters.pdf", Cluster.plot, device = "pdf", units="in", width=11, height=10, useDingbats = FALSE)



#Taken from colorBlindness::SteppedSequential5Steps
## colorBlindness::displayAvailablePalette(color="white")
cell.order<-c(colorBlindness::SteppedSequential5Steps[6:10],rev(RColorBrewer::brewer.pal(n = 8,name = "Reds")) ,colorBlindness::SteppedSequential5Steps[c(11:13,15, 16,18, 21:25)], "grey60")

names(cell.order)<-c(
  "Superficial", 
  "Intermediate",    
  "Suprabasal",
  "Basal",
  "SMG",
  
  "Foveolar_Differentiated",
  "Foveolar_Intermediate",
  "Neck-Cells",
  "Chief",        
  "Parietal",
  "Enteroendocrine_CHGA",
  "Enteroendocrine_GHRL", 
  "Enteroendocrine_GAST",
  
  
  
  "Enterocytes",
  "Enterocytes_Intermediate",
  "Intestinal_Undifferentiated",
  "Goblet",
  
  "Fibroblasts",
  "Endothelial",
  
  "B-Cells",
  "T-Cells",
  "Plasma-Cells",
  "Macrophages",
  "Mast",
  
  "Erythrocyte"
)
cell.plot<-ggplot(data.frame(UMAP1 = umap.data[,1],
                             UMAP2 = umap.data[,2],
                             Tissue = factor(sce$Celltypes_global, levels = names(cell.order)))) +
  geom_point(aes(UMAP1, UMAP2), size = 1, color = "black") +
  geom_point(aes(UMAP1, UMAP2, colour = Tissue), size = 0.5) + 
  theme_void() +
  ylim(umap.min.max) +
  xlim(umap.min.max) +
  guides(color=guide_legend(ncol=1, override.aes = list(size=4))) +
  # scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(9, "Set3"))))
  scale_color_manual(values = cell.order) 

print(cell.plot)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/Allumap_cells.tiff", cell.plot, device = "tiff", units="in", width=12, height=10)
ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/Allumap_cells.pdf", cell.plot, device = "pdf", units="in", width=12, height=10, useDingbats = FALSE)

cvdPlot(cell.plot)


# Visualise individual genes
gene1<-"CALD1"
expr.order<-order(logcounts(sce)[rowData(sce)$Symbol == gene1,])
print(ggplot(data.frame(UMAP1 = umap.data[expr.order,1],
                        UMAP2 = umap.data[expr.order,2],
                        gene = logcounts(sce)[rowData(sce)$Symbol == gene1,expr.order])) + 
        geom_point(aes(UMAP1, UMAP2, colour = gene)) + scale_colour_viridis(name = gene1, option = "B")+ 
        theme_cowplot(12) +
        ylim(umap.min.max) +
        xlim(umap.min.max)
)
# Study
print(ggplot(data.frame(UMAP1 = umap.data[,1],
                        UMAP2 = umap.data[,2],
                        Study = as.factor(colData(sce)$Study))) + 
        geom_point(aes(UMAP1, UMAP2, colour = Study), size = 0.5) + 
        scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(12, "Set3"), brewer.pal(8, "Set2")))+ 
        theme_cowplot(12) +
        ylim(umap.min.max) +
        xlim(umap.min.max)
)


# Is healthy
print(ggplot(data.frame(UMAP1 = umap.data[,1],
                        UMAP2 = umap.data[,2],
                        Status = as.factor(colData(sce)$Patient_type))) + 
        geom_point(aes(UMAP1, UMAP2, colour = Status), size = 0.5) + 
        scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(12, "Set3"), brewer.pal(8, "Set2")))+ 
        theme_cowplot(12) +
        ylim(umap.min.max) +
        xlim(umap.min.max)
)

# Is healthy and study
print(ggplot(data.frame(UMAP1 = umap.data[,1],
                        UMAP2 = umap.data[,2],
                        Combined = as.factor(paste(colData(sce)$Study, colData(sce)$Patient_type)))) + 
        geom_point(aes(UMAP1, UMAP2, colour = Combined), size = 0.5) + 
        scale_color_manual(values = c(brewer.pal(9, "Set1"), brewer.pal(12, "Set3"), brewer.pal(8, "Set2")))+ 
        theme_cowplot(12) +
        ylim(umap.min.max) +
        xlim(umap.min.max)
)

# Plot all patients individually 
# Generate patient colour vector
patient_vector <- c(brewer.pal(9, "Set1"), brewer.pal(12, "Set3"), brewer.pal(8, "Set2"))[1:length(unique(sce$Patient))]
names(patient_vector) <- unique(sce$Patient)

for.printing <- data.frame(UMAP1 = umap.data[,1],
                           UMAP2 = umap.data[,2],
                           Tissue = factor(sce$Tissue, levels = names(colour.palet)),
                           Patient = as.factor(sce$Patient),
                           Study = as.factor(sce$Study),
                           Time = as.factor(sce$Time),
                           CellType = factor(sce$Celltypes_global, levels = names(cell.order)),
                           Tissuetype = as.factor(sce$Tissuetypes_global),
                           Patientstatus = as.factor(sce$Patient_status),
                           Combined = as.factor(paste(colData(sce)$Study, colData(sce)$Patient_type)),
                           Combined2 = as.factor(paste(colData(sce)$Study, colData(sce)$Patient_status)),
                           Combined3 = as.factor(paste(colData(sce)$Patient, sce$Time))
)

qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))


for(i in names(colour.palet)) {
  # for(i in c("NE", "NSCJ", "BSCJ", "BE", "NG", "ND", "SMG","GIM", "CIM", "GM","NAG", "CAG")){
  # i <- "NE"
  
  
  for.printing.tmp<-for.printing[c(which(for.printing$Tissue != i),which(for.printing$Tissue == i)), ]  
  for.printing.tmp$Alpha <- ifelse(for.printing.tmp$Tissue == i, i, "other")
  # for.printing.tmp$Alpha <- ifelse(for.printing.tmp$Time == i & for.printing.tmp$Time == "0h", "other", i)
  # for.printing.tmp$Alpha <- ifelse(for.printing.tmp$Tissue == i & for.printing.tmp$Time == "0h" & for.printing.tmp$Study == "Sanger", i, "other")
  # 
  # # Visualise CALD1 genes
  # 
  # print(
  #   ggplot(data = for.printing.tmp) +
  #     geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(for.printing.tmp$Tissue != i)), rep(1, times = sum(for.printing.tmp$Tissue == i)))) +
  #     geom_point(aes(UMAP1, UMAP2, colour = gene, alpha = Alpha), size = 0.5) +
  #     scale_colour_viridis(name = gene1, option = "B") + 
  #     scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
  #     ggtitle(i)+ 
  #     theme_cowplot(12) +
  #     ylim(c(floor(min(reducedDims(sce)$umap[,1:2])), ceiling(max(reducedDims(sce)$umap[,1:2])))) +
  #     xlim(c(floor(min(reducedDims(sce)$umap[,1:2])), ceiling(max(reducedDims(sce)$umap[,1:2]))))
  # )
  # 
  # Visualize Tissue
  print(
    ggplot(data = for.printing.tmp) +
      geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(for.printing.tmp$Tissue != i)), rep(1, times = sum(for.printing.tmp$Tissue == i)))) +
      geom_point(aes(UMAP1, UMAP2, colour = Tissue, alpha = Alpha), size = 0.5) +
      scale_color_manual(values = colour.palet) + 
      scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
      ggtitle(i)+ 
      theme_cowplot(12) +
      ylim(umap.min.max) +
      xlim(umap.min.max)
  )
  # Visualize  Tissue type
  print(
    ggplot(data = for.printing.tmp) +
      geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(for.printing.tmp$Tissue != i)), rep(1, times = sum(for.printing.tmp$Tissue == i)))) +
      geom_point(aes(UMAP1, UMAP2, colour = Tissuetype, alpha = Alpha), size = 0.5) +
      scale_color_manual(values = col_vector) + 
      scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
      ggtitle(i)+ 
      theme_cowplot(12) +
      ylim(umap.min.max) +
      xlim(umap.min.max)
  )
  # Visualize Patient
  print(
    ggplot(data = for.printing.tmp) +
      geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(for.printing.tmp$Tissue != i)), rep(1, times = sum(for.printing.tmp$Tissue == i)))) +
      geom_point(aes(UMAP1, UMAP2, colour = Patient, alpha = Alpha), size = 0.5) +
      scale_color_manual(values = col_vector) + 
      scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
      ggtitle(i)+ 
      theme_cowplot(12) +
      ylim(umap.min.max) +
      xlim(umap.min.max)
  )
  
  # Visualize Cell type
  celltype.individual.plot <- ggplot(data = for.printing.tmp) +
    geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(for.printing.tmp$Tissue != i)), rep(1, times = sum(for.printing.tmp$Tissue == i)))) +
    geom_point(aes(UMAP1, UMAP2, colour = CellType, alpha = Alpha), size = 0.5) +
    scale_color_manual(values = cell.order) + 
    scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
    ggtitle(i)+ 
    theme_void() +
    guides(color=guide_legend(ncol=1, override.aes = list(size=4))) +
    ylim(umap.min.max) +
    xlim(umap.min.max)
  
  print(celltype.individual.plot)
  ggsave(paste0("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/",i,"_umap_cells.tiff"), celltype.individual.plot, device = "tiff", units="in", width=12, height=10)
  
  # Visualize Study
  print(
    ggplot(data = for.printing.tmp) +
      geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(for.printing.tmp$Tissue != i)), rep(1, times = sum(for.printing.tmp$Tissue == i)))) +
      geom_point(aes(UMAP1, UMAP2, colour = Study, alpha = Alpha), size = 0.5) +
      scale_color_manual(values = col_vector) + 
      scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
      ggtitle(i)+ 
      theme_cowplot(12) +
      ylim(umap.min.max) +
      xlim(umap.min.max)
  )
  # Visualize Patient Status
  print(
    ggplot(data = for.printing.tmp) +
      geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(for.printing.tmp$Tissue != i)), rep(1, times = sum(for.printing.tmp$Tissue == i)))) +
      geom_point(aes(UMAP1, UMAP2, colour = Patientstatus, alpha = Alpha), size = 0.5) +
      scale_color_manual(values = col_vector) + 
      scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
      ggtitle(i)+ 
      theme_cowplot(12) +
      ylim(umap.min.max) +
      xlim(umap.min.max)
  )
  
  
}


i <- c("NE", "SMG")


for.printing.tmp<-for.printing[c(which(!(for.printing$Tissue %in% i)),which(for.printing$Tissue %in% i)), ]  
for.printing.tmp$Alpha <- ifelse(for.printing.tmp$Tissue %in% i, "Esophagus", "other")

# Visualize Esophageal tissues

Eso.tissues <- ggplot(data = for.printing.tmp) +
  geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(!(for.printing.tmp$Tissue %in% i))), rep(1, times = sum(for.printing.tmp$Tissue %in% i)))) +
  geom_point(aes(UMAP1, UMAP2, colour = Tissue, alpha = Alpha), size = 0.5) +
  scale_color_manual(values = colour.palet) + 
  scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
  ggtitle("Esophageal")+ 
  theme_void() +
  guides(color=guide_legend(ncol=1, override.aes = list(size=4))) +
  ylim(umap.min.max) +
  xlim(umap.min.max)
plot(Eso.tissues)
ggsave(paste0("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/","Esophageal","_umap_cells.tiff"), Eso.tissues, device = "tiff", units="in", width=12, height=10)



i <- c("NSCJ", "NG", "NGB")


for.printing.tmp<-for.printing[c(which(!(for.printing$Tissue %in% i)),which(for.printing$Tissue %in% i)), ]  
for.printing.tmp$Alpha <- ifelse(for.printing.tmp$Tissue %in% i, "Esophagus", "other")

# Visualize Esophageal tissues

Stomach.tissues <- ggplot(data = for.printing.tmp) +
  geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(!(for.printing.tmp$Tissue %in% i))), rep(1, times = sum(for.printing.tmp$Tissue %in% i)))) +
  geom_point(aes(UMAP1, UMAP2, colour = Tissue, alpha = Alpha), size = 0.5) +
  scale_color_manual(values = colour.palet) + 
  scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
  ggtitle("Stomach")+ 
  theme_void() +
  guides(color=guide_legend(ncol=1, override.aes = list(size=4))) +
  ylim(umap.min.max) +
  xlim(umap.min.max)
plot(Stomach.tissues)
ggsave(paste0("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/","Stomach","_umap_cells.tiff"), Stomach.tissues, device = "tiff", units="in", width=12, height=10)


i <- c("ND", "Ileum", "Colon", "Rectum")


for.printing.tmp<-for.printing[c(which(!(for.printing$Tissue %in% i)),which(for.printing$Tissue %in% i)), ]  
for.printing.tmp$Alpha <- ifelse(for.printing.tmp$Tissue %in% i, "Esophagus", "other")

# Visualize Esophageal tissues

Intestine.tissues <- ggplot(data = for.printing.tmp) +
  geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(!(for.printing.tmp$Tissue %in% i))), rep(1, times = sum(for.printing.tmp$Tissue %in% i)))) +
  geom_point(aes(UMAP1, UMAP2, colour = Tissue, alpha = Alpha), size = 0.5) +
  scale_color_manual(values = colour.palet) + 
  scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
  ggtitle("Intestine")+ 
  theme_void() +
  guides(color=guide_legend(ncol=1, override.aes = list(size=4))) +
  ylim(umap.min.max) +
  xlim(umap.min.max)
plot(Intestine.tissues)
ggsave(paste0("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/","Intestine","_umap_cells.tiff"), Intestine.tissues, device = "tiff", units="in", width=12, height=10)

i <- c("GM", "BE", "BSCJ")


for.printing.tmp<-for.printing[c(which(!(for.printing$Tissue %in% i)),which(for.printing$Tissue %in% i)), ]  
for.printing.tmp$Alpha <- ifelse(for.printing.tmp$Tissue %in% i, "Esophagus", "other")

# Visualize Esophageal tissues

BE.tissues <- ggplot(data = for.printing.tmp) +
  geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(!(for.printing.tmp$Tissue %in% i))), rep(1, times = sum(for.printing.tmp$Tissue %in% i)))) +
  geom_point(aes(UMAP1, UMAP2, colour = Tissue, alpha = Alpha), size = 0.5) +
  scale_color_manual(values = colour.palet) + 
  scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
  ggtitle("BE")+ 
  theme_void() +
  guides(color=guide_legend(ncol=1, override.aes = list(size=4))) +
  ylim(umap.min.max) +
  xlim(umap.min.max)
plot(BE.tissues)
ggsave(paste0("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/","BE.tissue","_umap_cells.tiff"), BE.tissues, device = "tiff", units="in", width=12, height=10)

i <- c("GIM", "CIM", "NAG", "CAG")


for.printing.tmp<-for.printing[c(which(!(for.printing$Tissue %in% i)),which(for.printing$Tissue %in% i)), ]  
for.printing.tmp$Alpha <- ifelse(for.printing.tmp$Tissue %in% i, "Esophagus", "other")

# Visualize Esophageal tissues

IM.tissues <- ggplot(data = for.printing.tmp) +
  geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(!(for.printing.tmp$Tissue %in% i))), rep(1, times = sum(for.printing.tmp$Tissue %in% i)))) +
  geom_point(aes(UMAP1, UMAP2, colour = Tissue, alpha = Alpha), size = 0.5) +
  scale_color_manual(values = colour.palet) + 
  scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
  ggtitle("IM")+ 
  theme_void() +
  guides(color=guide_legend(ncol=1, override.aes = list(size=4))) +
  ylim(umap.min.max) +
  xlim(umap.min.max)
plot(IM.tissues)
ggsave(paste0("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/","IM.tissues","_umap_cells.tiff"), IM.tissues, device = "tiff", units="in", width=12, height=10)



for(i in levels(for.printing$Patient)){
  # i <- "Patient22"
  
  for.printing.tmp<-for.printing[c(which(for.printing$Patient != i),which(for.printing$Patient == i)), ]  
  for.printing.tmp$Alpha <- ifelse(for.printing.tmp$Patient == i, i, "other")
  
  
  print(
    ggplot(data = for.printing.tmp) +
      geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(for.printing.tmp$Patient != i)), rep(1, times = sum(for.printing.tmp$Patient == i)))) +
      geom_point(aes(UMAP1, UMAP2, colour = Tissue, alpha = Alpha), size = 0.5) +
      scale_color_manual(values = colour.palet) + 
      scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
      ggtitle(i)+ 
      theme_cowplot(12) +
      ylim(umap.min.max) +
      xlim(umap.min.max)
  )
  
  # Visualize Cell type
  print(
    ggplot(data = for.printing.tmp) +
      geom_point(aes(UMAP1, UMAP2, alpha = Alpha), size = 1, color = "black", alpha = c(rep(0.01, times = sum(for.printing.tmp$Tissue != i)), rep(1, times = sum(for.printing.tmp$Tissue == i)))) +
      geom_point(aes(UMAP1, UMAP2, colour = CellType, alpha = Alpha), size = 0.5) +
      scale_color_manual(values = col_vector) + 
      scale_alpha_manual(values = c(i = 1 , "other" = 0.00)) +
      ggtitle(i)+ 
      theme_cowplot(12) +
      ylim(umap.min.max) +
      xlim(umap.min.max)
  )
}












print(table(colData(sce)$Patient, colData(sce)$Tissue))

print(colSums(table(colData(sce)$Patient, colData(sce)$Tissue)))

print(table(sce$Global_cluster_selected, colData(sce)$Tissue))

reshape2::melt(print(table(sce$Celltypes_global, colData(sce)$Tissue)))




```

### Make bargraphs

```{r}
colour.palet.boxplot <- c("NE" = "#990F0F", 
                  "NSCJ" = "#CC5151",
                  "SMG" = "#FFB2B2",
                  "GM" = "#E5B17E",
                  "BE" = "#99540F",
                  "BSCJ" = "#CC8E51",
                  
                  "NG" = "#6B990F",
                  "NGB" = "#A3CC51",
                  "NAG" = "#0F6B99",
                  "CAG" = "#2C85B2",
                  "CIM" = "#7EC3E5",
                  "GIM" = "#51A3CC",
                  
                  "ND" = "#260F99",
                  "Ileum" = "#422CB2",
                  "Colon" = "#6551CC",
                  "Rectum" = "#8F7EE5")
countsdata<-reshape2::melt(print(table(sce$Celltypes_global, colData(sce)$Tissue)))
colnames(countsdata)<-c("CellType", "Tissue", "Count")
countsdata$CellType<-factor(countsdata$CellType, levels = names(cell.order))
countsdata$Tissue <- factor(countsdata$Tissue, levels = names(colour.palet.boxplot))
countsdata$TissueType <- factor("Normal", levels = c("Normal", "Esophageal IM", "Stomach IM"))
countsdata$TissueType[countsdata$Tissue %in% c("BE", "BSCJ", "GM")] <- "Esophageal IM"
countsdata$TissueType[countsdata$Tissue %in% c("NAG", "CAG", "GIM", "CIM")] <- "Stomach IM"



countsdata<-countsdata[!(countsdata$CellType %in%   c(  "Superficial", 
                                                        "Intermediate",    
                                                        "Suprabasal",
                                                        "Basal",
                                                        # "SMG",
                                                        
                                                        "Fibroblasts",
                                                        "Endothelial",
                                                        
                                                        "B-Cells",
                                                        "T-Cells",
                                                        "Plasma-Cells",
                                                        "Macrophages",
                                                        "Mast",
                                                        
                                                        "Erythrocyte")),]
countsdata<-countsdata[!(countsdata$Tissue %in%   c("NE")),]
boxplot.celltypes<-ggplot(data = countsdata, aes(x = Tissue, y = Count, fill = CellType)) + geom_bar(position = "fill", stat = "identity") +   scale_fill_manual(values = cell.order) + theme_cowplot(12)  +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  facet_wrap(vars(TissueType), drop = TRUE,scales = "free_x", nrow = 1)+ theme(legend.position = "none")
plot(boxplot.celltypes)

ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/Boxplot.celltypes.pdf", boxplot.celltypes, device = "pdf", units="in", width=15, height=10, useDingbats = FALSE)

```

# T-SCAN analysis

# Perform pseudotime analysis

Here I will use TSCAN algorithm to reconstruct the trajectory following this manual: https://bioconductor.org/books/release/OSCA/trajectory-analysis.html


```{r}
# Read in all data
sce <- readRDS("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/All_sce_selected_corrected_witout_Sanger_with_Ji_after_exclusion2.rds")

# Perform PCA
HVG.genes<-modelGeneVar(sce, block = sce$Sample)
top.sce <- getTopHVGs(HVG.genes, n=2000)

set.seed(12345)
# PCA <- prcomp(t(corrected))
# save a slot
# reducedDims(sce)$PCA <- PCA$x
sce <- runPCA(sce, subset_row=top.sce) 


```

# run TSCAN

```{r}
# Run TSCAN on PCA data with outgroup option on and wiht cell types as clusters and with mnn mode on. Only focus on epithelial cells

cl <- makeCluster(7) #not to overload your computer
registerDoParallel(cl)

# Run in parallel wiht multiple values of outscale factor to identify a clear separation between cell types of glandular, squamous and columnar cell types

pseudo.mnn.list <-  foreach(i=c(2.5, 2.6,  2.7, 2.75, 2.8, 2.9, 3)) %dopar% {
  tmp = TSCAN::quickPseudotime(sce[,sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular") ], use.dimred="PCA", outgroup=TRUE, clusters =  sce$Global_cluster_selected[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular") ], with.mnn = TRUE,outscale = i)
  #do other things if you want
  return(tmp) 
}
#foreach(j=c(15, 100)) %:%
stopCluster(cl)

plot(pseudo.mnn.list[[2]]$mst)


#Aggregate data across tissue clusters
by.cluster<-aggregateAcrossCells(sce[,sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular") ], ids = sce$Global_cluster_selected[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular") ])

# Get line data between connected clusters
line.data <- reportEdges(by.cluster, mst=pseudo.mnn.list[[2]]$mst, clusters=NULL, use.dimred="umap_MinDist_0.2_N_Neighbors_15")

tscan.plot<-ggplot(data.frame(umap1 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,1],
                              umap2 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,2],
                              Alpha = ifelse(sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular"), "Epi", "other"))) +
  geom_point(aes(umap1, umap2, alpha = Alpha), size = 1, colour = "black") + # Plot all data in black as background
  scale_alpha_manual(values = c("Epi" = 1 , "other" = 0.01)) + # Change the alpha of the non-epithelial black dots to 1% to highlight only the epithelial cells
  geom_point(data= data.frame(umap1 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,1],
                              umap2 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,2],
                              Cell =  factor(sce$Celltypes_global, levels = names(cell.order))
  )[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular") ,], # Plot data for each epithelial cell again
  mapping = aes(umap1, umap2, colour = Cell), size = 0.5) + # make the dots smaller and colour by cell type
  scale_color_manual(values = cell.order) + # add cell type colour values
  geom_line(data=line.data, mapping=aes(x=dim1, y=dim2, group=edge)) + # add line data connecting the clusters (not cell types)
  # geom_text(data= aggregate(reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular"),], list(sce$Global_cluster_selected[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular")]), mean),
  #           mapping = aes(V1, V2, label = Group.1), colour = "red", size = 6) +
  #theme_cowplot(12) 
  guides(color=guide_legend(ncol=1, override.aes = list(size=4))) + #Plot legend in a single column
  theme_void()

print(tscan.plot)

ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/Allumap_withtscan.tiff", tscan.plot, device = "tiff", units="in", width=12, height=10)

tscan.plot.all<-ggplot(data.frame(umap1 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,1],
                                  umap2 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,2])) +
  # Alpha = ifelse(sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular"), "Epi", "other"))) +
  geom_point(aes(umap1, umap2), size = 1, colour = "black") + # Plot all data in black as background
  # scale_alpha_manual(values = c("Epi" = 1 , "other" = 0.01)) + # Change the alpha of the non-epithelial black dots to 1% to highlight only the epithelial cells
  geom_point(data= data.frame(umap1 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,1],
                              umap2 = reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[,2],
                              Cell =  factor(sce$Celltypes_global, levels = names(cell.order))
  ), # Plot data for each epithelial cell again
  mapping = aes(umap1, umap2, colour = Cell), size = 0.5) + # make the dots smaller and colour by cell type
  scale_color_manual(values = cell.order) + # add cell type colour values
  geom_line(data=line.data, mapping=aes(x=dim1, y=dim2, group=edge)) + # add line data connecting the clusters (not cell types)
  # geom_text(data= aggregate(reducedDims(sce)$umap_MinDist_0.2_N_Neighbors_15[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular"),], list(sce$Global_cluster_selected[sce$Tissuetypes_global %in% c("Squamous", "Columnar", "Glandular")]), mean),
  #           mapping = aes(V1, V2, label = Group.1), colour = "red", size = 6) +
  #theme_cowplot(12) 
  guides(color=guide_legend(ncol=1, override.aes = list(size=4))) + #Plot legend in a single column
  theme_void()

print(tscan.plot.all)

ggsave("~/Dropbox/Postdoc/2021-05-19_Gastric_IM/Results/Figures/Figure_1/Allumap_all_withtscan.tiff", tscan.plot.all, device = "tiff", units="in", width=12, height=10)

```



# End Matter

To finish get session info:


```{r Endnote, include=TRUE, echo=TRUE, warning=FALSE, eval=TRUE, message=FALSE, tidy=TRUE}
sessionInfo()
```

